/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated.history'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated.search'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated.admin.logs'
import { Route as AuthenticatedResultsSearchIdRouteImport } from './routes/_authenticated.results.$searchId'
import { Route as ApiAutomationsCancelRouteImport } from './routes/api.automations.cancel'
import { Route as ApiAutomationsReconcileRouteImport } from './routes/api.automations.reconcile'
import { Route as ApiAutomationsStartRouteImport } from './routes/api.automations.start'
import { Route as ApiAutomationsStatusRouteImport } from './routes/api.automations.status'
import { Route as ApiPublicAutomationControlRouteImport } from './routes/api.public.automation-control'
import { Route as ApiPublicIntegrationHealthRouteImport } from './routes/api.public.integration-health'
import { Route as ApiPublicResultsRouteImport } from './routes/api.public.results'
import { Route as ApiPublicStartSearchRouteImport } from './routes/api.public.start-search'
import { Route as ApiPublicWhatsappStatusRouteImport } from './routes/api.public.whatsapp-status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResultsSearchIdRoute =
  AuthenticatedResultsSearchIdRouteImport.update({
    id: '/results/$searchId',
    path: '/results/$searchId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAutomationsCancelRoute = ApiAutomationsCancelRouteImport.update({
  id: '/api/automations/cancel',
  path: '/api/automations/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutomationsReconcileRoute = ApiAutomationsReconcileRouteImport.update({
  id: '/api/automations/reconcile',
  path: '/api/automations/reconcile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutomationsStartRoute = ApiAutomationsStartRouteImport.update({
  id: '/api/automations/start',
  path: '/api/automations/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutomationsStatusRoute = ApiAutomationsStatusRouteImport.update({
  id: '/api/automations/status',
  path: '/api/automations/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAutomationControlRoute =
  ApiPublicAutomationControlRouteImport.update({
    id: '/api/public/automation-control',
    path: '/api/public/automation-control',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntegrationHealthRoute =
  ApiPublicIntegrationHealthRouteImport.update({
    id: '/api/public/integration-health',
    path: '/api/public/integration-health',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicResultsRoute = ApiPublicResultsRouteImport.update({
  id: '/api/public/results',
  path: '/api/public/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStartSearchRoute = ApiPublicStartSearchRouteImport.update({
  id: '/api/public/start-search',
  path: '/api/public/start-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappStatusRoute = ApiPublicWhatsappStatusRouteImport.update({
  id: '/api/public/whatsapp-status',
  path: '/api/public/whatsapp-status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset': typeof AuthResetRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/results/$searchId': typeof AuthenticatedResultsSearchIdRoute
  '/api/automations/cancel': typeof ApiAutomationsCancelRoute
  '/api/automations/reconcile': typeof ApiAutomationsReconcileRoute
  '/api/automations/start': typeof ApiAutomationsStartRoute
  '/api/automations/status': typeof ApiAutomationsStatusRoute
  '/api/public/automation-control': typeof ApiPublicAutomationControlRoute
  '/api/public/integration-health': typeof ApiPublicIntegrationHealthRoute
  '/api/public/results': typeof ApiPublicResultsRoute
  '/api/public/start-search': typeof ApiPublicStartSearchRoute
  '/api/public/whatsapp-status': typeof ApiPublicWhatsappStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset': typeof AuthResetRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/results/$searchId': typeof AuthenticatedResultsSearchIdRoute
  '/api/automations/cancel': typeof ApiAutomationsCancelRoute
  '/api/automations/reconcile': typeof ApiAutomationsReconcileRoute
  '/api/automations/start': typeof ApiAutomationsStartRoute
  '/api/automations/status': typeof ApiAutomationsStatusRoute
  '/api/public/automation-control': typeof ApiPublicAutomationControlRoute
  '/api/public/integration-health': typeof ApiPublicIntegrationHealthRoute
  '/api/public/results': typeof ApiPublicResultsRoute
  '/api/public/start-search': typeof ApiPublicStartSearchRoute
  '/api/public/whatsapp-status': typeof ApiPublicWhatsappStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset': typeof AuthResetRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/results/$searchId': typeof AuthenticatedResultsSearchIdRoute
  '/api/automations/cancel': typeof ApiAutomationsCancelRoute
  '/api/automations/reconcile': typeof ApiAutomationsReconcileRoute
  '/api/automations/start': typeof ApiAutomationsStartRoute
  '/api/automations/status': typeof ApiAutomationsStatusRoute
  '/api/public/automation-control': typeof ApiPublicAutomationControlRoute
  '/api/public/integration-health': typeof ApiPublicIntegrationHealthRoute
  '/api/public/results': typeof ApiPublicResultsRoute
  '/api/public/start-search': typeof ApiPublicStartSearchRoute
  '/api/public/whatsapp-status': typeof ApiPublicWhatsappStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/search'
    | '/settings'
    | '/auth/callback'
    | '/auth/reset'
    | '/admin/logs'
    | '/results/$searchId'
    | '/api/automations/cancel'
    | '/api/automations/reconcile'
    | '/api/automations/start'
    | '/api/automations/status'
    | '/api/public/automation-control'
    | '/api/public/integration-health'
    | '/api/public/results'
    | '/api/public/start-search'
    | '/api/public/whatsapp-status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/search'
    | '/settings'
    | '/auth/callback'
    | '/auth/reset'
    | '/admin/logs'
    | '/results/$searchId'
    | '/api/automations/cancel'
    | '/api/automations/reconcile'
    | '/api/automations/start'
    | '/api/automations/status'
    | '/api/public/automation-control'
    | '/api/public/integration-health'
    | '/api/public/results'
    | '/api/public/start-search'
    | '/api/public/whatsapp-status'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/auth/callback'
    | '/auth/reset'
    | '/_authenticated/admin/logs'
    | '/_authenticated/results/$searchId'
    | '/api/automations/cancel'
    | '/api/automations/reconcile'
    | '/api/automations/start'
    | '/api/automations/status'
    | '/api/public/automation-control'
    | '/api/public/integration-health'
    | '/api/public/results'
    | '/api/public/start-search'
    | '/api/public/whatsapp-status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiAutomationsCancelRoute: typeof ApiAutomationsCancelRoute
  ApiAutomationsReconcileRoute: typeof ApiAutomationsReconcileRoute
  ApiAutomationsStartRoute: typeof ApiAutomationsStartRoute
  ApiAutomationsStatusRoute: typeof ApiAutomationsStatusRoute
  ApiPublicAutomationControlRoute: typeof ApiPublicAutomationControlRoute
  ApiPublicIntegrationHealthRoute: typeof ApiPublicIntegrationHealthRoute
  ApiPublicResultsRoute: typeof ApiPublicResultsRoute
  ApiPublicStartSearchRoute: typeof ApiPublicStartSearchRoute
  ApiPublicWhatsappStatusRoute: typeof ApiPublicWhatsappStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/results/$searchId': {
      id: '/_authenticated/results/$searchId'
      path: '/results/$searchId'
      fullPath: '/results/$searchId'
      preLoaderRoute: typeof AuthenticatedResultsSearchIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/automations/cancel': {
      id: '/api/automations/cancel'
      path: '/api/automations/cancel'
      fullPath: '/api/automations/cancel'
      preLoaderRoute: typeof ApiAutomationsCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/automations/reconcile': {
      id: '/api/automations/reconcile'
      path: '/api/automations/reconcile'
      fullPath: '/api/automations/reconcile'
      preLoaderRoute: typeof ApiAutomationsReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/automations/start': {
      id: '/api/automations/start'
      path: '/api/automations/start'
      fullPath: '/api/automations/start'
      preLoaderRoute: typeof ApiAutomationsStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/automations/status': {
      id: '/api/automations/status'
      path: '/api/automations/status'
      fullPath: '/api/automations/status'
      preLoaderRoute: typeof ApiAutomationsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/automation-control': {
      id: '/api/public/automation-control'
      path: '/api/public/automation-control'
      fullPath: '/api/public/automation-control'
      preLoaderRoute: typeof ApiPublicAutomationControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integration-health': {
      id: '/api/public/integration-health'
      path: '/api/public/integration-health'
      fullPath: '/api/public/integration-health'
      preLoaderRoute: typeof ApiPublicIntegrationHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/results': {
      id: '/api/public/results'
      path: '/api/public/results'
      fullPath: '/api/public/results'
      preLoaderRoute: typeof ApiPublicResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/start-search': {
      id: '/api/public/start-search'
      path: '/api/public/start-search'
      fullPath: '/api/public/start-search'
      preLoaderRoute: typeof ApiPublicStartSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp-status': {
      id: '/api/public/whatsapp-status'
      path: '/api/public/whatsapp-status'
      fullPath: '/api/public/whatsapp-status'
      preLoaderRoute: typeof ApiPublicWhatsappStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedResultsSearchIdRoute: typeof AuthenticatedResultsSearchIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedResultsSearchIdRoute: AuthenticatedResultsSearchIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetRoute: typeof AuthResetRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetRoute: AuthResetRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiAutomationsCancelRoute: ApiAutomationsCancelRoute,
  ApiAutomationsReconcileRoute: ApiAutomationsReconcileRoute,
  ApiAutomationsStartRoute: ApiAutomationsStartRoute,
  ApiAutomationsStatusRoute: ApiAutomationsStatusRoute,
  ApiPublicAutomationControlRoute: ApiPublicAutomationControlRoute,
  ApiPublicIntegrationHealthRoute: ApiPublicIntegrationHealthRoute,
  ApiPublicResultsRoute: ApiPublicResultsRoute,
  ApiPublicStartSearchRoute: ApiPublicStartSearchRoute,
  ApiPublicWhatsappStatusRoute: ApiPublicWhatsappStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
